### ISSUE TITLE
issue with unique username

### ISSUE THREAD

**Issue by Bhoft** [eureka-clusters/portal-backend#13]
a username column was added to the admin_users table with this commit
https://github.com/eureka-clusters/portal-backend/commit/bdcf50df54e770fab460171ecf57c39464e0430a

The `setUsername` function isn't called (yet) on the user creation in the `UserService:findOrCreateUserFromGenericUser` https://github.com/eureka-clusters/portal-backend/blob/main/module/admin/src/Service/UserService.php#L27

As currently the user table could contain multiple entries already the \doctrine-module orm:schema-tool:update couldn't executed as the username with be empty for every existing entry which isn't unique. 

I  also don't know if a unique username is feasible between multiple external tools. 
I thought we have added the email address as unique user identifier?

**Comment by japaveh** [comment]
I had to add the username to be consistent with the bshaffer module, but I forgot to add the username to function. This can simply be the same as the email address so we keep the email address as the application unique identifier
