### ISSUE TITLE
export url can be called as guest user

### ISSUE THREAD

**Issue by Bhoft** [eureka-clusters/portal-backend#25]
The export listener is able to be called when user is not logged in and shows an warning:
/api/statistics/results/project/download/csv

error which is shown:
`<br />
<b>Warning</b>:  Trying to access array offset on value of type null in <b>portal-backend-main\module\api\src\V1\Rest\StatisticsResource\Download\ProjectListener.php</b> on line <b>34</b><br />
{"type":"http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html","title":"Not Found","status":404,"detail":"Entity not found."}`

affected listeners:
https://github.com/eureka-clusters/portal-backend/blob/8cd2653ff76f45528919241da9d68f020b73961b/module/api/src/V1/Rest/StatisticsResource/Download/PartnerListener.php#L36
https://github.com/eureka-clusters/portal-backend/blob/8cd2653ff76f45528919241da9d68f020b73961b/module/api/src/V1/Rest/StatisticsResource/Download/ProjectListener.php#L34

**Comment by japaveh** [comment]
Fixed

<img width="874" alt="image" src="https://user-images.githubusercontent.com/1028237/231177177-5995cc20-87b3-4084-a23d-09abe3185fda.png">
