### ISSUE TITLE
OAuth2Controller findLatestClient doesn't work for local development

### ISSUE THREAD

**Issue by Bhoft** [eureka-clusters/portal-backend#26]
I have an issue with my local development that i had to add an additional client to the database.
I had cloned the live database at some time and had to add a new client to the database to be able to set the returnUrl for this client (which runs on localhost:3000)

therefore this line must be changed:
https://github.com/eureka-clusters/portal-backend/blob/main/module/application/src/Controller/OAuth2Controller.php#L120

Suggestion change `findLatestClient` to get a client by client_id and have a fixed client_id set in the application settings.

`$oAuthClient = $this->oAuthService->findClientByClientId('frontend');`

**Comment by japaveh** [comment]
This has been fixed by creating services in the database
